M48
; DRILL file {KiCad (6.0.7)} date Tue Oct 25 14:44:26 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-10-25T14:44:26+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.7)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0866
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0984
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.1378
%
G90
G05
T1
X0.0984Y-0.0984
X0.0984Y-2.1063
X4.1142Y-0.0984
X4.1142Y-2.1063
T2
X0.4441Y-2.0685
X0.8441Y-2.0709
T3
X2.3264Y-0.7114
T0
M30
